spring.docker.compose.file=docker-compose-dev.yaml
server.port=8091

spring.application.name=dev-app

spring.datasource.username=isma
spring.datasource.password=1234

spring.jpa.show-sql=false

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f27273b544ff99
spring.mail.password=a8b82c9dbaa5a4

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=sandbox.smtp.mailtrap.io