services:
  
  database:
    image: 'pgvector/pgvector:0.8.1-pg18-trixie'
    ports:
    - '5432:5432'
    environment:
    - 'POSTGRES_USER=isma'
    - 'POSTGRES_DB=mydatabasetfg'
    - 'POSTGRES_PASSWORD=1234'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U isma -d mydatabasetfg"]
        interval: 5s
        timeout: 5s
        retries: 5
  app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      #Configuration spring
      SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: true
      SPRING_MAIN_WEB_APPLICATION_TYPE: servlet
      #Conection database postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mydatabasetfg
      SPRING_DATASOURCE_USERNAME: isma
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      #Connection ollama model
      SPRING_AI_OLLAMA_BASE_URL: http://host.docker.internal:11434
      SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL: llama3.1:8b
      SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_MODEL: nomic-embed-text:latest
      #Connection Spring ai vector
      SPRING_AI_VECTORSTORE_PGVECTOR_INITIALIZE_SCHEMA: "true"
      SPRING_AI_VECTORSTORE_PGVECTOR_DIMENSIONS: "768"
      #LANGCHAIN4J_OLLAMA_CHAT_MODEL_BASE_URL: http://host.docker.internal:11434
      #LANGCHAIN4J_OLLAMA_CHAT_MODEL_NAME: deepseek-ocr:latest
volumes:
  postgres_data: